# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"read_config": "00_core.ipynb",
         "parse_dataset_archive_name": "00_core.ipynb",
         "parse_dataset_archive_version": "00_core.ipynb",
         "next_version": "00_core.ipynb",
         "make_dataset_archive_folder": "00_core.ipynb",
         "StorageClientABC": "00_core.ipynb",
         "LocalStorageClient": "00_core.ipynb",
         "AzureStorageClient": "00_core.ipynb",
         "AwsStorageClient": "00_core.ipynb",
         "new_storage_client": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://pete88b.github.io/storage_tools/"

git_url = "https://github.com/pete88b/storage_tools/tree/master/"

def custom_doc_links(name): return None
