# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://pete88b.github.io/storage_tools/"

git_url = "https://github.com/pete88b/storage_tools/tree/master/"

def custom_doc_links(name): return None
